version: '3.9'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagamentos
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
